package browser_history

import (
	"context"
	"strings"

	"mcpyeahyouknowme/core"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const historySearchExample = `{"query":"github","sort":"recent","limit":20,"offset":0}`
const historyListExample = `{"sort":"recent","limit":20,"offset":0}`

// registerTools wires read-only browser history tools without doing snapshot refreshes in MCP requests.
func registerTools(src *Source, s *server.MCPServer) {
	prefix := src.Name() + "_"
	s.AddTool(core.NewReadOnlyTool(prefix+"search",
		core.ToolDescription("Search browser history visits from the latest daemon snapshot.", historySearchExample),
		mcp.WithString("query", mcp.Required(), mcp.Description("Substring match against URL and page title")),
		mcp.WithString("sort", mcp.Description("Sort order: recent or oldest (default recent)")),
		mcp.WithNumber("limit", mcp.Description("Maximum rows to return (default 50, max 200)")),
		mcp.WithNumber("offset", mcp.Description("Pagination offset (default 0)")),
	), func(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return handleSearchTool(src, req, true)
	})

	s.AddTool(core.NewReadOnlyTool(prefix+"list",
		core.ToolDescription("List browser history visits from the latest daemon snapshot.", historyListExample),
		mcp.WithString("sort", mcp.Description("Sort order: recent or oldest (default recent)")),
		mcp.WithNumber("limit", mcp.Description("Maximum rows to return (default 50, max 200)")),
		mcp.WithNumber("offset", mcp.Description("Pagination offset (default 0)")),
	), func(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return handleSearchTool(src, req, false)
	})
}

// Handles one browser history search/list tool call using the latest local snapshot generated by the daemon.
func handleSearchTool(src *Source, req mcp.CallToolRequest, requireQuery bool) (*mcp.CallToolResult, error) {
	cfg := loadBrowserHistoryConfig(src.dataDir)
	if normalizeBrowser(cfg.Browser) == "" {
		return mcp.NewToolResultError("browser_history is not configured; run 'mcpyeahyouknowme browser_history enable <chrome|brave>'"), nil
	}

	args := req.GetArguments()
	query := readOptionalString(args, "query")
	if requireQuery {
		requiredQuery, errResult := core.RequireStringArgument(req, "query", historySearchExample)
		if errResult != nil {
			return errResult, nil
		}
		query = requiredQuery
	}
	sortOrder := readOptionalString(args, "sort")
	if sortOrder == "" {
		sortOrder = "recent"
	}
	if sortOrder != "recent" && sortOrder != "oldest" {
		return mcp.NewToolResultError(`sort must be "recent" or "oldest"`), nil
	}
	limit, offset := normalizePagination(core.IntArg(args, "limit", 50), core.IntArg(args, "offset", 0))

	db, err := src.openSnapshotForRead()
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	defer db.Close()

	rows, err := listVisits(db, query, sortOrder, limit, offset)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return core.JsonResult(rows)
}

// Reads an optional string argument while trimming whitespace for predictable matching behavior.
func readOptionalString(args map[string]interface{}, key string) string {
	v, ok := args[key]
	if !ok {
		return ""
	}
	s, ok := v.(string)
	if !ok {
		return ""
	}
	return strings.TrimSpace(s)
}
